version: '3'

services:
  db:
    image: mysql:5.7
    # build:
    #   context: db
    container_name: db
    restart: always
    tty: true
    #volumes:
    #  - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build:
      context: app
    container_name: app
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s node index.js
    depends_on:
      - db

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge